### ISSUE TITLE
Hash collision

### ISSUE THREAD

**Issue by Aurora0000** [JacobMisirian/JacHash#1]
abcdd == abcde in JaHash, evidently this is an issue.

**Comment by Aurora0000** [comment]
In fact, there are serious flaws with the hash.

In any 8 letter string:
zzzzz**x**z**x**
The '**x**' characters don't seem to matter at all, and all of those will collide.

In a 5 letter string:
zzzz**x**

The '**x**' character collides with at least one other character.

**Comment by JacobMisirian** [comment]
Okay, I have changed the core of the hash algorithm to loosely be modeled after SHA. Those two no longer collide although the strings are similar. I am going to be doing more research to fix this. Thank you very much for bringing the previous to my attention Aurora.
